### ISSUE TITLE
How to install tf 1.4.0

### ISSUE THREAD

**Issue by Aquadrox** [OlafenwaMoses/ImageAI#415]
Hi all,

couldn't find the answer yet, I'm desperatly trying to install tf 1.4.0 cause it's not working on 2.0.
Could anyone tell me how to proceed?

Thanks

**Comment by huangl6** [comment]
1.4.0 is a really old version. if you mean 1.14.0 (still outdated, should probably use 1.15.0 or 1.13.1 if you experience the '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string' error) 
the pip command is pip install tensorflow-gpu==1.15.0 
or
pip install tensorflow==1.15.0 if you don't have a gpu.

**Comment by rola93** [comment]
Did you solve it @Aquadrox ? Can you close this issue ? Thanks @huangl6 for your answer!
