### ISSUE TITLE
Issues with TensorFlow on Google Colab

### ISSUE THREAD

**Issue by huangl6** [OlafenwaMoses/ImageAI#414]
Hi, I'm having issues getting the Custom Detection Model up and running on Google Colab and was hoping for some help.

I initially tried with tensorflow-gpu 1.15.0 but I got the '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string' error. 

I then tried downgrading to 1.13.1 like the guide says, but now I'm greeted with the error: Failed to load the native TensorFlow runtime.

Any ideas on what I should do or what I'm doing wrong? I have made sure that I've selected GPU as the hardware accelerator.

Thanks!

**Comment by nguyengiakhiem0501** [comment]
Image AI train model using tensorflow-gpu 1.13.1. Tensorflow-gpu 1.13.1  work well with Cuda 10.0 (or newer). Google colad is using cuda 10.0.1. You should install tensorflow-gpu to you computer to train your model. (sorry, my Englist is bad)

**Comment by huangl6** [comment]
I see. My computer is not very powerful so I would prefer to do it on Colab. Is there any other solution? (install Cuda 10.0?)

**Comment by huangl6** [comment]
I think I solved it. Basically I purged everything Nvidia from the Colab notebook and then manually installed Cuda 10.0.130: 

`!sudo apt-get purge nvidia*`
`!sudo wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64`
`!sudo dpkg -i cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64`
`!sudo apt-key add /var/cuda-repo-<version>/7fa2af80.pub`
`!sudo apt-get update`
`!sudo apt-get install cuda=10.0.130-1`

Gonna close this issue now. Thanks for the tip @nguyengiakhiem0501 !

**Comment by EhtishamSabir** [comment]
#I fixed this using 
!pip install keras==2.2.4
!pip install tensorflow-gpu==1.13.1
!sudo apt-get purge nvidia*
!sudo wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64
!sudo dpkg -i cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64
!sudo apt-key add /var/cuda-repo-<version>/7fa2af80.pub
!sudo apt-get update
!sudo apt-get install cuda=10.0.130-1

**Comment by luisERH** [comment]
someone can share google colab notebook pre configured for ImageAI?

**Comment by EhtishamSabir** [comment]
I'll with in next few hours
